version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: banking_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - banking_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bank-network

  app:
    restart: always
    container_name: banking_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    networks:
      - bank-network

volumes:
  banking_postgres_data:

networks:
  bank-network:
    driver: bridge