version: '3.8'

volumes:
  pg_banking:

services:
  banking:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pg_banking:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5442:5432"